MetaDataFormat = "yaml"
theme = "solstice"
languageCode = "en-us"
title = "EGerrit"

[params]
  description = "EGerrit"
  author = "EGerrit team"

[taxonomies]
  tag = "tags"
  group = "groups"

# [[menu.main]]
#     name = "about"
#     pre = ""
#     url = "/about/"
# [[menu.main]]
#     name = "other"
#     parent = "about"
#     pre = ""
#     url = "/other/"
